MCU = RP2040
BOARD = GENERIC_RP2040

VIAL_ENABLE = yes
VIA_ENABLE = yes
LTO_ENABLE = yes

BOOTMAGIC_ENABLE = lite
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
NKRO_ENABLE = yes
